# Generated by Django 2.2.28 on 2022-07-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
